### ISSUE TITLE
ERROR: Service 'uwsgi' failed to build

### ISSUE THREAD

**Issue by rbrecheisen** [vsoch/django-nginx-upload#12]
Hi,

I just pulled the repo and ran docker-compose up -d straightaway. Unfortunately, the build failed with the following output:

 => ERROR [5/9] RUN pip install -r /tmp/requirements.txt                                                                                                   0.3s 
------                                                                                                                                                          
 > [5/9] RUN pip install -r /tmp/requirements.txt:                                                                                                              
#9 0.244 Traceback (most recent call last):                                                                                                                     
#9 0.244   File "/usr/local/bin/pip", line 7, in <module>                                                                                                       
#9 0.244     from pip._internal.cli.main import main                                                                                                            
#9 0.244   File "/usr/local/lib/python3.5/site-packages/pip/_internal/cli/main.py", line 58
#9 0.244     sys.stderr.write(f"ERROR: {exc}")
#9 0.244                                    ^
#9 0.244 SyntaxError: invalid syntax
------
executor failed running [/bin/sh -c pip install -r /tmp/requirements.txt]: exit code: 1
ERROR: Service 'uwsgi' failed to build : Build failed

Any idea why this happens? I'm running Docker 20.10.6 for Mac OS Mojave

Any help would be appreciated!

Ralph

**Comment by vsoch** [comment]
That's strange - let me give it a shot!

**Comment by vsoch** [comment]
Ah okay I see what's going on! During the build we upgrade pip, and pip added that format string (the third to last line) that is technically invalid syntax for the Python version. I'll put in a PR with a newer Python base for you to test!

**Comment by vsoch** [comment]
okay here is a PR for you to test! 

https://github.com/vsoch/django-nginx-upload/pull/13

When this looks good, we can merge and release.

**Comment by rbrecheisen** [comment]
Hi, not sure I correctly pulled your branch (git checkout -b update/python-base) but I'm still seeing the same error when I run docker-compose up -d.
